version: '3'
services:
  keto:
    image: oryd/keto:v0.8.0-alpha.2
    ports:
      - '4466:4466'
      - '4467:4467'
    command: serve -c /home/ory/keto.yml
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=memory
    restart: on-failure
    volumes:
      - type: bind
        source: './contrib/keto'
        target: '/home/ory'
